# Build and publish

trigger:
- main

pool:
  vmImage: 'windows-latest'
  
variables:
  solution: 'src/SqlSherlock.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'DotNet Build: $(buildConfiguration)'
    
- task: PublishBuildArtifacts@1
  displayName: Export ArtifactStagingDirectory
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
