# Build and publish

trigger:
- main

pool:
  vmImage: 'windows-latest'
  
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'DotNet Build: $(buildConfiguration)'

- script: dotnet publish
  displayName: 'DotNet Publish'
  
- task: PublishBuildArtifacts@1
  displayName: Export ArtifactStagingDirectory
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
