<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SqlSherlock</RootNamespace>
    <AssemblyName>SqlSherlock</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Content\bootstrap-theme.css" />
    <Content Remove="wwwroot\Content\bootstrap-theme.css.map" />
    <Content Remove="wwwroot\Content\bootstrap-theme.min.css" />
    <Content Remove="wwwroot\Content\bootstrap-theme.min.css.map" />
    <Content Remove="wwwroot\Content\bootstrap.css" />
    <Content Remove="wwwroot\Content\bootstrap.css.map" />
    <Content Remove="wwwroot\Content\bootstrap.min.css" />
    <Content Remove="wwwroot\Content\bootstrap.min.css.map" />
    <Content Remove="wwwroot\Content\Site.css" />
    <Content Remove="wwwroot\Content\vue-datepicker-local.css" />
    <Content Remove="wwwroot\img\loading1.svg" />
    <Content Remove="wwwroot\img\logo.png" />
    <Content Remove="wwwroot\Scripts\App\QueryFlowComponent.js" />
    <Content Remove="wwwroot\Scripts\App\VueApp.js" />
    <Content Remove="wwwroot\Scripts\vue-datepicker-local.js" />
    <Content Remove="wwwroot\Scripts\vue.js" />
    <Content Remove="wwwroot\Scripts\vue.min.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SqlSherlock.Data\SqlSherlock.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Content\bootstrap-theme.css" />
    <None Include="wwwroot\Content\bootstrap-theme.css.map" />
    <None Include="wwwroot\Content\bootstrap-theme.min.css" />
    <None Include="wwwroot\Content\bootstrap-theme.min.css.map" />
    <None Include="wwwroot\Content\bootstrap.css" />
    <None Include="wwwroot\Content\bootstrap.css.map" />
    <None Include="wwwroot\Content\bootstrap.min.css" />
    <None Include="wwwroot\Content\bootstrap.min.css.map" />
    <None Include="wwwroot\Content\Site.css" />
    <None Include="wwwroot\Content\vue-datepicker-local.css" />
    <None Include="wwwroot\fonts\glyphicons-halflings-regular.eot" />
    <None Include="wwwroot\fonts\glyphicons-halflings-regular.svg" />
    <None Include="wwwroot\fonts\glyphicons-halflings-regular.ttf" />
    <None Include="wwwroot\fonts\glyphicons-halflings-regular.woff" />
    <None Include="wwwroot\fonts\glyphicons-halflings-regular.woff2" />
    <None Include="wwwroot\img\loading1.svg" />
    <None Include="wwwroot\img\logo.png" />
    <None Include="wwwroot\Scripts\App\QueryFlowComponent.js" />
    <None Include="wwwroot\Scripts\App\VueApp.js" />
    <None Include="wwwroot\Scripts\vue-datepicker-local.js" />
    <None Include="wwwroot\Scripts\vue.js" />
    <None Include="wwwroot\Scripts\vue.min.js" />
  </ItemGroup>

</Project>